cs-aspnet-mvc-crud/Models/task_note.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs_aspnet_mvc_crud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_note
    {
        public int id { get; set; }
        public int task_id { get; set; }
        public int note_id { get; set; }
        public int user_id { get; set; }
    
        public virtual note note { get; set; }
        public virtual task task { get; set; }
        public virtual user user { get; set; }
    }
}

cs-aspnet-mvc-crud/Controllers/TaskNoteController.cs
using System;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using System.Linq;
using cs_aspnet_mvc_crud.Models;
using cs_aspnet_mvc_crud.Middleware.Auth;
using PagedList;


namespace cs_aspnet_mvc_crud.Controllers
{
    public class TaskNoteController : BaseController
    {
        // GET: TaskNote
        [UserAuthorization(userActionId: 41)]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.isAdmin = isAdmin;

            ViewBag.CurrentSort = sortOrder;
            ViewBag.IdSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewBag.TaskNameSortParm = String.IsNullOrEmpty(sortOrder) ? "task_name_desc" : "";
            ViewBag.NoteNameSortParm = String.IsNullOrEmpty(sortOrder) ? "note_name_desc" : "";
            ViewBag.UserUsernameSortParm = String.IsNullOrEmpty(sortOrder) ? "user_username_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var tasksNotes = from o in entityModel.TaskNote select o;

            if (!String.IsNullOrEmpty(searchString))
            {
                tasksNotes = tasksNotes.Where(o =>
                    o.task.name.Contains(searchString)
                    || o.note.name.Contains(searchString)
                    || o.user.username.Contains(searchString)
                );
            }

            switch (sortOrder)
            {
                case "id_desc":
                    tasksNotes = tasksNotes.OrderByDescending(o => o.id);
                    break;
                case "task_name_desc":
                    tasksNotes = tasksNotes.OrderByDescending(o => o.task.name);
                    break;
                case "note_name_desc":
                    tasksNotes = tasksNotes.OrderByDescending(o => o.note.name);
                    break;
                case "user_username_desc":
                    tasksNotes = tasksNotes.OrderByDescending(o => o.user.username);
                    break;
                default:
                    tasksNotes = tasksNotes.OrderBy(o => o.id);
                    break;
            }
            int pageNumber = (page ?? 1);

            return View(tasksNotes.ToPagedList(pageNumber, this.pageSize));
        }

        // GET: TaskNote
        [UserAuthorization(userActionId: 41)]
        public async Task<ActionResult> GetAll()
        {
            var task_note = entityModel.TaskNote.Include(t => t.note).Include(t => t.task).Include(t => t.user);
            return View(await task_note.ToListAsync());
        }

        // GET: TaskNote/Details/5
        [UserAuthorization(userActionId: 42)]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            task_note task_note = await entityModel.TaskNote.FindAsync(id);
            if (task_note == null)
            {
                return HttpNotFound();
            }
            return View(task_note);
        }

        // GET: TaskNote/Create
        [UserAuthorization(userActionId: 43)]
        public ActionResult Create()
        {
            ViewBag.note_id = new SelectList(entityModel.Note, "id", "name");
            ViewBag.task_id = new SelectList(entityModel.Task, "id", "name");
            ViewBag.user_id = new SelectList(entityModel.User, "id", "username");
            return View();
        }

        // POST: TaskNote/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserAuthorization(userActionId: 43)]
        public async Task<ActionResult> Create([Bind(Include = "id,task_id,note_id,user_id")] task_note task_note)
        {
            if (ModelState.IsValid)
            {
                entityModel.TaskNote.Add(task_note);
                await entityModel.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.note_id = new SelectList(entityModel.Note, "id", "name", task_note.note_id);
            ViewBag.task_id = new SelectList(entityModel.Task, "id", "name", task_note.task_id);
            ViewBag.user_id = new SelectList(entityModel.User, "id", "username", task_note.user_id);
            return View(task_note);
        }

        // GET: TaskNote/Edit/5
        [UserAuthorization(userActionId: 44)]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            task_note task_note = await entityModel.TaskNote.FindAsync(id);
            if (task_note == null)
            {
                return HttpNotFound();
            }
            ViewBag.note_id = new SelectList(entityModel.Note, "id", "name", task_note.note_id);
            ViewBag.task_id = new SelectList(entityModel.Task, "id", "name", task_note.task_id);
            ViewBag.user_id = new SelectList(entityModel.User, "id", "username", task_note.user_id);
            return View(task_note);
        }

        // POST: TaskNote/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserAuthorization(userActionId: 44)]
        public async Task<ActionResult> Edit([Bind(Include = "id,task_id,note_id,user_id")] task_note task_note)
        {
            if (ModelState.IsValid)
            {
                entityModel.Entry(task_note).State = EntityState.Modified;
                await entityModel.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.note_id = new SelectList(entityModel.Note, "id", "name", task_note.note_id);
            ViewBag.task_id = new SelectList(entityModel.Task, "id", "name", task_note.task_id);
            ViewBag.user_id = new SelectList(entityModel.User, "id", "username", task_note.user_id);
            return View(task_note);
        }

        // GET: TaskNote/Delete/5
        [UserAuthorization(userActionId: 45)]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            task_note task_note = await entityModel.TaskNote.FindAsync(id);
            if (task_note == null)
            {
                return HttpNotFound();
            }
            return View(task_note);
        }

        // POST: TaskNote/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [UserAuthorization(userActionId: 45)]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            task_note task_note = await entityModel.TaskNote.FindAsync(id);
            entityModel.TaskNote.Remove(task_note);
            await entityModel.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                entityModel.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

cs-aspnet-mvc-crud/Views/TaskNote/Create.cshtml
@model cs_aspnet_mvc_crud.Models.task_note

@{
    ViewBag.Title = "Create";
    ViewBag.Model = "Task Note";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="col mx-auto">
        <div class="p-4 p-md-5 border rounded-3 bg-light">
            <h4>@ViewBag.Title @ViewBag.Model</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group mb-3">

                <div class="control-label">Task</div>
                <div class="col-md-10">
                    @Html.DropDownList("task_id", null, htmlAttributes: new { @class = "form-select" })
                    @Html.ValidationMessageFor(model => model.task_id, "", new { @class = "text-danger" })
                </div>

                <div class="control-label">Note</div>
                <div class="col-md-10">
                    @Html.DropDownList("note_id", null, htmlAttributes: new { @class = "form-select" })
                    @Html.ValidationMessageFor(model => model.note_id, "", new { @class = "text-danger" })
                </div>

                <div class="control-label">User</div>
                <div class="col-md-10">
                    @Html.DropDownList("user_id", null, htmlAttributes: new { @class = "form-select" })
                    @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "text-danger" })
                </div>

            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-lg btn-dark" })
                    <input type="submit" value="Add" class="btn btn-lg btn-success" />
                </div>
            </div>
        </div>
    </div>
}

cs-aspnet-mvc-crud/Views/TaskNote/Delete.cshtml
@model cs_aspnet_mvc_crud.Models.task_note

@{
    ViewBag.Title = "Delete";
    ViewBag.Model = "Task Note";
    ViewBag.ModelRelation1 = "Task";
    ViewBag.ModelRelation2 = "Note";
    ViewBag.ModelRelation3 = "User";
}

<div class="col mx-auto">
    <div class="p-4 p-md-5 border rounded-3 bg-light">

        <div class="alert alert-danger" role="alert">
            Are you sure you want to delete this @ViewBag.Model?
        </div>

        <div class="accordion mb-3" id="accordionOne">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button text-white bg-danger" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        @ViewBag.Title of this @ViewBag.Model
                    </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionOne">
                    <div class="accordion-body">
                        <div class="container">
                            <div class="row">
                                <div class="col-3"><b>Id</b></div>
                                <div class="col">@Html.DisplayFor(model => model.id)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Task Id</b></div>
                                <div class="col">@Html.DisplayFor(model => model.task_id)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Note Id</b></div>
                                <div class="col">@Html.DisplayFor(model => model.note_id)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>User Id</b></div>
                                <div class="col">@Html.DisplayFor(model => model.user_id)</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="accordion mb-3" id="accordionTwo">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingTwo">
                    <button class="accordion-button text-white bg-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                        Related to @ViewBag.ModelRelation1
                    </button>
                </h2>
                <div id="collapseTwo" class="accordion-collapse collapse show" aria-labelledby="headingTwo" data-bs-parent="#accordionTwo">
                    <div class="accordion-body">
                        <div class="container">
                            <div class="row">
                                <div class="col-3"><b>Id</b></div>
                                <div class="col">@Html.DisplayFor(model => model.task.id)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Name</b></div>
                                <div class="col">@Html.DisplayFor(model => model.task.name)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Description</b></div>
                                <div class="col">@Html.DisplayFor(model => model.task.description)</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="accordion mb-3" id="accordionThree">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingThree">
                    <button class="accordion-button text-white bg-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                        Related to @ViewBag.ModelRelation2
                    </button>
                </h2>
                <div id="collapseThree" class="accordion-collapse collapse show" aria-labelledby="headingThree" data-bs-parent="#accordionThree">
                    <div class="accordion-body">
                        <div class="container">
                            <div class="row">
                                <div class="col-3"><b>Id</b></div>
                                <div class="col">@Html.DisplayFor(model => model.note.id)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Name</b></div>
                                <div class="col">@Html.DisplayFor(model => model.note.name)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Description</b></div>
                                <div class="col">@Html.DisplayFor(model => model.note.description)</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="accordion mb-3" id="accordionFour">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingFour">
                    <button class="accordion-button text-white bg-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour">
                        Related to @ViewBag.ModelRelation3
                    </button>
                </h2>
                <div id="collapseFour" class="accordion-collapse collapse show" aria-labelledby="headingFour" data-bs-parent="#accordionFour">
                    <div class="accordion-body">
                        <div class="container">
                            <div class="row">
                                <div class="col-3"><b>Id</b></div>
                                <div class="col">@Html.DisplayFor(model => model.user.id)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Username</b></div>
                                <div class="col">@Html.DisplayFor(model => model.user.username)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Email</b></div>
                                <div class="col">@Html.DisplayFor(model => model.user.email)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>First Name</b></div>
                                <div class="col">@Html.DisplayFor(model => model.user.first_name)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Last Name</b></div>
                                <div class="col">@Html.DisplayFor(model => model.user.last_name)</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-lg btn-dark" })
                <input type="submit" value="Delete" class="btn btn-lg btn-danger" />
            </div>
        </div>

    </div>
</div>

cs-aspnet-mvc-crud/Views/TaskNote/Details.cshtml
@model cs_aspnet_mvc_crud.Models.task_note

@{
    ViewBag.Title = "Details";
    ViewBag.Model = "Task Note";
    ViewBag.ModelRelation1 = "Task";
    ViewBag.ModelRelation2 = "Note";
    ViewBag.ModelRelation3 = "User";
}

<div class="col mx-auto">
    <div class="p-4 p-md-5 border rounded-3 bg-light">

        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">@ViewBag.Title @ViewBag.Model</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    @Html.ActionLink("Return", "Index", null, new { @class = "btn btn-sm btn-dark bi bi-backspace" })
                </div>
            </div>
        </div>

        <div class="accordion mb-3" id="accordionOne">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button text-white bg-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        @ViewBag.Title of this @ViewBag.Model
                    </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionOne">
                    <div class="accordion-body">
                        <div class="container">
                            <div class="row">
                                <div class="col-3"><b>Id</b></div>
                                <div class="col">@Html.DisplayFor(model => model.id)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Task Id</b></div>
                                <div class="col">@Html.DisplayFor(model => model.task_id)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Note Id</b></div>
                                <div class="col">@Html.DisplayFor(model => model.note_id)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>User Id</b></div>
                                <div class="col">@Html.DisplayFor(model => model.user_id)</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="accordion mb-3" id="accordionTwo">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingTwo">
                    <button class="accordion-button text-white bg-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                        Related to @ViewBag.ModelRelation1
                    </button>
                </h2>
                <div id="collapseTwo" class="accordion-collapse collapse show" aria-labelledby="headingTwo" data-bs-parent="#accordionTwo">
                    <div class="accordion-body">
                        <div class="container">
                            <div class="row">
                                <div class="col-3"><b>Id</b></div>
                                <div class="col">@Html.DisplayFor(model => model.task.id)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Name</b></div>
                                <div class="col">@Html.DisplayFor(model => model.task.name)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Description</b></div>
                                <div class="col">@Html.DisplayFor(model => model.task.description)</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="accordion mb-3" id="accordionThree">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingThree">
                    <button class="accordion-button text-white bg-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                        Related to @ViewBag.ModelRelation2
                    </button>
                </h2>
                <div id="collapseThree" class="accordion-collapse collapse show" aria-labelledby="headingThree" data-bs-parent="#accordionThree">
                    <div class="accordion-body">
                        <div class="container">
                            <div class="row">
                                <div class="col-3"><b>Id</b></div>
                                <div class="col">@Html.DisplayFor(model => model.note.id)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Name</b></div>
                                <div class="col">@Html.DisplayFor(model => model.note.name)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Description</b></div>
                                <div class="col">@Html.DisplayFor(model => model.note.description)</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="accordion mb-3" id="accordionFour">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingFour">
                    <button class="accordion-button text-white bg-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour">
                        Related to @ViewBag.ModelRelation3
                    </button>
                </h2>
                <div id="collapseFour" class="accordion-collapse collapse show" aria-labelledby="headingFour" data-bs-parent="#accordionFour">
                    <div class="accordion-body">
                        <div class="container">
                            <div class="row">
                                <div class="col-3"><b>Id</b></div>
                                <div class="col">@Html.DisplayFor(model => model.user.id)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Username</b></div>
                                <div class="col">@Html.DisplayFor(model => model.user.username)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Email</b></div>
                                <div class="col">@Html.DisplayFor(model => model.user.email)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>First Name</b></div>
                                <div class="col">@Html.DisplayFor(model => model.user.first_name)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Last Name</b></div>
                                <div class="col">@Html.DisplayFor(model => model.user.last_name)</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

cs-aspnet-mvc-crud/Views/TaskNote/Edit.cshtml
@model cs_aspnet_mvc_crud.Models.task_note

@{
    ViewBag.Title = "Edit";
    ViewBag.Model = "Task Note";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="col mx-auto">
        <div class="p-4 p-md-5 border rounded-3 bg-light">
            <h4>@ViewBag.Title @ViewBag.Model</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)

            <div class="form-group mb-3">

                <div class="control-label">Task</div>
                <div class="col-md-10">
                    @Html.DropDownList("task_id", null, htmlAttributes: new { @class = "form-select" })
                    @Html.ValidationMessageFor(model => model.task_id, "", new { @class = "text-danger" })
                </div>

                <div class="control-label">Note</div>
                <div class="col-md-10">
                    @Html.DropDownList("note_id", null, htmlAttributes: new { @class = "form-select" })
                    @Html.ValidationMessageFor(model => model.note_id, "", new { @class = "text-danger" })
                </div>

                <div class="control-label">User</div>
                <div class="col-md-10">
                    @Html.DropDownList("user_id", null, htmlAttributes: new { @class = "form-select" })
                    @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "text-danger" })
                </div>

            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-lg btn-dark" })
                    <input type="submit" value="Save Changes" class="btn btn-lg btn-primary" />
                </div>
            </div>
        </div>
    </div>
}

cs-aspnet-mvc-crud/Views/TaskNote/Index.cshtml
@model PagedList.IPagedList<cs_aspnet_mvc_crud.Models.task_note>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Tasks Notes";
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">@ViewBag.Title</h1>

    @using (Html.BeginForm("Index", "TaskNote", FormMethod.Get))
    {
        <div class="input-group">
            <input type="submit" class="btn btn-outline-secondary" value="Search" />
            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", placeholder = "Input name or description" })
        </div>
    }

    <div class="btn-toolbar mb-2 mb-md-0">
        @Html.ActionLink("Add", "Create", null, new { @class = "btn btn-success bi bi-plus-circle" })
    </div>
</div>

<div class="table-responsive">
    <table class="table table-hover caption-top">
        <caption>@ViewBag.Title</caption>
        <thead>
            <tr>
                <th scope="col" class="col-3">Actions</th>
                <th scope="col">@Html.ActionLink("Id", "Index", new { sortOrder = ViewBag.IdSortParm, currentFilter = ViewBag.CurrentFilter })</th>
                <th scope="col">@Html.ActionLink("Task", "Index", new { sortOrder = ViewBag.TaskNameSortParm, currentFilter = ViewBag.CurrentFilter })</th>
                <th scope="col">@Html.ActionLink("Note", "Index", new { sortOrder = ViewBag.NoteNameSortParm, currentFilter = ViewBag.CurrentFilter })</th>
                <th scope="col">@Html.ActionLink("User", "Index", new { sortOrder = ViewBag.UserUsernameSortParm, currentFilter = ViewBag.CurrentFilter })</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(" ", "Details", new { id = item.id }, new { @class = "btn btn-outline-info bi bi-eye" })
                        @Html.ActionLink(" ", "Edit", new { id = item.id }, new { @class = "btn btn-outline-warning bi bi-pencil" })
                        @Html.ActionLink(" ", "Delete", new { id = item.id }, new { @class = "btn btn-outline-danger bi bi-trash" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.note.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.task.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.user.username)
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</div>