cs-aspnet-mvc-crud/Models/user_permission.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs_aspnet_mvc_crud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_permission
    {
        public int id { get; set; }
        public int user_position_id { get; set; }
        public int user_action_id { get; set; }
    
        public virtual user_action user_action { get; set; }
        public virtual user_position user_position { get; set; }
    }
}

cs-aspnet-mvc-crud/Controllers/UserPermissionController.cs
using System;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using System.Linq;
using cs_aspnet_mvc_crud.Models;
using cs_aspnet_mvc_crud.Middleware.Auth;
using PagedList;

namespace cs_aspnet_mvc_crud.Controllers
{
    public class UserPermissionController : BaseController
    {
        // GET: UserPermission
        [UserAuthorization(userActionId: 21)]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.isAdmin = isAdmin;

            ViewBag.CurrentSort = sortOrder;
            ViewBag.IdSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewBag.UserPositionNameSortParm = String.IsNullOrEmpty(sortOrder) ? "user_position_name_desc" : "";
            ViewBag.UserActionNameSortParm = String.IsNullOrEmpty(sortOrder) ? "user_action_name_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var usersPermissions = from o in entityModel.UserPermission select o;

            if (!String.IsNullOrEmpty(searchString))
            {
                usersPermissions = usersPermissions.Where(o =>
                    o.user_position.name.Contains(searchString)
                    || o.user_action.name.Contains(searchString)
                );
            }

            switch (sortOrder)
            {
                case "id_desc":
                    usersPermissions = usersPermissions.OrderByDescending(o => o.id);
                    break;
                case "user_position_name_desc":
                    usersPermissions = usersPermissions.OrderByDescending(o => o.user_position.name);
                    break;
                case "user_action_name_desc":
                    usersPermissions = usersPermissions.OrderByDescending(o => o.user_action.name);
                    break;
                default:
                    usersPermissions = usersPermissions.OrderBy(o => o.id);
                    break;
            }
            int pageNumber = (page ?? 1);

            return View(usersPermissions.ToPagedList(pageNumber, this.pageSize));
        }

        // GET: UserPermission
        [UserAuthorization(userActionId: 21)]
        public async Task<ActionResult> GetAll()
        {
            var user_permission = entityModel.UserPermission.Include(u => u.user_action).Include(u => u.user_position);
            return View(await user_permission.ToListAsync());
        }

        // GET: UserPermission/Details/5
        [UserAuthorization(userActionId: 22)]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user_permission user_permission = await entityModel.UserPermission.FindAsync(id);
            if (user_permission == null)
            {
                return HttpNotFound();
            }
            return View(user_permission);
        }

        // GET: UserPermission/Create
        [UserAuthorization(userActionId: 23)]
        public ActionResult Create()
        {
            ViewBag.user_action_id = new SelectList(entityModel.UserAction, "id", "name");
            ViewBag.user_position_id = new SelectList(entityModel.UserPosition, "id", "name");
            return View();
        }

        // POST: UserPermission/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserAuthorization(userActionId: 23)]
        public async Task<ActionResult> Create([Bind(Include = "id,user_position_id,user_action_id")] user_permission user_permission)
        {
            if (ModelState.IsValid)
            {
                entityModel.UserPermission.Add(user_permission);
                await entityModel.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.user_action_id = new SelectList(entityModel.UserAction, "id", "name", user_permission.user_action_id);
            ViewBag.user_position_id = new SelectList(entityModel.UserPosition, "id", "name", user_permission.user_position_id);
            return View(user_permission);
        }

        // GET: UserPermission/Edit/5
        [UserAuthorization(userActionId: 24)]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user_permission user_permission = await entityModel.UserPermission.FindAsync(id);
            if (user_permission == null)
            {
                return HttpNotFound();
            }
            ViewBag.user_action_id = new SelectList(entityModel.UserAction, "id", "name", user_permission.user_action_id);
            ViewBag.user_position_id = new SelectList(entityModel.UserPosition, "id", "name", user_permission.user_position_id);
            return View(user_permission);
        }

        // POST: UserPermission/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserAuthorization(userActionId: 24)]
        public async Task<ActionResult> Edit([Bind(Include = "id,user_position_id,user_action_id")] user_permission user_permission)
        {
            if (ModelState.IsValid)
            {
                entityModel.Entry(user_permission).State = EntityState.Modified;
                await entityModel.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.user_action_id = new SelectList(entityModel.UserAction, "id", "name", user_permission.user_action_id);
            ViewBag.user_position_id = new SelectList(entityModel.UserPosition, "id", "name", user_permission.user_position_id);
            return View(user_permission);
        }

        // GET: UserPermission/Delete/5
        [UserAuthorization(userActionId: 25)]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user_permission user_permission = await entityModel.UserPermission.FindAsync(id);
            if (user_permission == null)
            {
                return HttpNotFound();
            }
            return View(user_permission);
        }

        // POST: UserPermission/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [UserAuthorization(userActionId: 25)]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            user_permission user_permission = await entityModel.UserPermission.FindAsync(id);
            entityModel.UserPermission.Remove(user_permission);
            await entityModel.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                entityModel.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

cs-aspnet-mvc-crud/Views/UserPermission/Create.cshtml
@model cs_aspnet_mvc_crud.Models.user_permission

@{
    ViewBag.Title = "Create";
    ViewBag.Model = "User Permission";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="col mx-auto">
        <div class="p-4 p-md-5 border rounded-3 bg-light">
            <h4>@ViewBag.Title @ViewBag.Model</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group mb-3">

                <div class="control-label">User Position</div>
                <div class="col-md-10">
                    @Html.DropDownList("user_position_id", null, htmlAttributes: new { @class = "form-select" })
                    @Html.ValidationMessageFor(model => model.user_position_id, "", new { @class = "text-danger" })
                </div>

                <div class="control-label">User Action</div>
                <div class="col-md-10">
                    @Html.DropDownList("user_action_id", null, htmlAttributes: new { @class = "form-select" })
                    @Html.ValidationMessageFor(model => model.user_action_id, "", new { @class = "text-danger" })
                </div>

            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-lg btn-dark" })
                    <input type="submit" value="Add" class="btn btn-lg btn-success" />
                </div>
            </div>
        </div>
    </div>
}

cs-aspnet-mvc-crud/Views/UserPermission/Delete.cshtml
@model cs_aspnet_mvc_crud.Models.user_permission

@{
    ViewBag.Title = "Delete";
    ViewBag.Model = "User Permission";
    ViewBag.ModelRelation1 = "User Position";
    ViewBag.ModelRelation2 = "User Action";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="col mx-auto">
        <div class="p-4 p-md-5 border rounded-3 bg-light">
            <div class="alert alert-danger" role="alert">
                Are you sure you want to delete this @ViewBag.Model?
            </div>

            <div class="accordion mb-3" id="accordionOne">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                        <button class="accordion-button text-white bg-danger" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            @ViewBag.Title this @ViewBag.Model
                        </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionOne">
                        <div class="accordion-body">
                            <div class="container">
                                <div class="row">
                                    <div class="col-3"><b>Id</b></div>
                                    <div class="col">@Html.DisplayFor(model => model.id)</div>
                                </div>
                                <div class="row">
                                    <div class="col-3"><b>Position Id</b></div>
                                    <div class="col">@Html.DisplayFor(model => model.user_position_id)</div>
                                </div>
                                <div class="row">
                                    <div class="col-3"><b>Action Id</b></div>
                                    <div class="col">@Html.DisplayFor(model => model.user_action_id)</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="accordion mb-3" id="accordionTwo">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingTwo">
                        <button class="accordion-button text-white bg-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                            Related to @ViewBag.ModelRelation
                        </button>
                    </h2>
                    <div id="collapseTwo" class="accordion-collapse collapse show" aria-labelledby="headingTwo" data-bs-parent="#accordionTwo">
                        <div class="accordion-body">
                            <div class="container">
                                <div class="row">
                                    <div class="col-3"><b>Id</b></div>
                                    <div class="col">@Html.DisplayFor(model => model.user_position.id)</div>
                                </div>
                                <div class="row">
                                    <div class="col-3"><b>Name</b></div>
                                    <div class="col">@Html.DisplayFor(model => model.user_position.name)</div>
                                </div>
                                <div class="row">
                                    <div class="col-3"><b>Description</b></div>
                                    <div class="col">@Html.DisplayFor(model => model.user_position.description)</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="accordion mb-3" id="accordionThree">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingThree">
                        <button class="accordion-button text-white bg-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                            Related to @ViewBag.ModelRelation
                        </button>
                    </h2>
                    <div id="collapseThree" class="accordion-collapse collapse show" aria-labelledby="headingThree" data-bs-parent="#accordionThree">
                        <div class="accordion-body">
                            <div class="container">
                                <div class="row">
                                    <div class="col-3"><b>Id</b></div>
                                    <div class="col">@Html.DisplayFor(model => model.user_action.id)</div>
                                </div>
                                <div class="row">
                                    <div class="col-3"><b>Name</b></div>
                                    <div class="col">@Html.DisplayFor(model => model.user_action.name)</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-lg btn-dark" })
                    <input type="submit" value="Delete" class="btn btn-lg btn-danger" />
                </div>
            </div>

        </div>
    </div>
}

cs-aspnet-mvc-crud/Views/UserPermission/Details.cshtml
@model cs_aspnet_mvc_crud.Models.user_permission

@{
    ViewBag.Title = "Details";
    ViewBag.Model = "User Permission";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="col mx-auto">
        <div class="p-4 p-md-5 border rounded-3 bg-light">
            <h4>@ViewBag.Title @ViewBag.Model</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group mb-3">

                <div class="control-label">User Position</div>
                <div class="col-md-10">
                    @Html.DropDownList("user_position_id", null, htmlAttributes: new { @class = "form-select" })
                    @Html.ValidationMessageFor(model => model.user_position_id, "", new { @class = "text-danger" })
                </div>

                <div class="control-label">User Action</div>
                <div class="col-md-10">
                    @Html.DropDownList("user_action_id", null, htmlAttributes: new { @class = "form-select" })
                    @Html.ValidationMessageFor(model => model.user_action_id, "", new { @class = "text-danger" })
                </div>

            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-lg btn-dark" })
                    <input type="submit" value="Add" class="btn btn-lg btn-success" />
                </div>
            </div>
        </div>
    </div>
}

cs-aspnet-mvc-crud/Views/UserPermission/Edit.cshtml
@model cs_aspnet_mvc_crud.Models.user_permission

@{
    ViewBag.Title = "Edit";
    ViewBag.Model = "User Permission";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="col mx-auto">
        <div class="p-4 p-md-5 border rounded-3 bg-light">
            <h4>@ViewBag.Title @ViewBag.Model</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)

            <div class="form-group mb-3">

                <div class="control-label">User Position</div>
                <div class="col-md-10">
                    @Html.DropDownList("user_position_id", null, htmlAttributes: new { @class = "form-select" })
                    @Html.ValidationMessageFor(model => model.user_position_id, "", new { @class = "text-danger" })
                </div>

                <div class="control-label">User Action</div>
                <div class="col-md-10">
                    @Html.DropDownList("user_action_id", null, htmlAttributes: new { @class = "form-select" })
                    @Html.ValidationMessageFor(model => model.user_action_id, "", new { @class = "text-danger" })
                </div>

            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-lg btn-dark" })
                    <input type="submit" value="Save Changes" class="btn btn-lg btn-primary" />
                </div>
            </div>
        </div>
    </div>
}

cs-aspnet-mvc-crud/Views/UserPermission/Index.cshtml
@model PagedList.IPagedList<cs_aspnet_mvc_crud.Models.user_permission>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Users Permissions";
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">@ViewBag.Title</h1>

    @using (Html.BeginForm("Index", "UserPermission", FormMethod.Get))
    {
        <div class="input-group">
            <input type="submit" class="btn btn-outline-secondary" value="Search" />
            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", placeholder = "Input name" })
        </div>
    }

    <div class="btn-toolbar mb-2 mb-md-0">
        @Html.ActionLink("Add", "Create", null, new { @class = "btn btn-success bi bi-plus-circle" })
    </div>
</div>

<div class="table-responsive">
    <table class="table table-hover caption-top">
        <caption>@ViewBag.Title</caption>
        <thead>
            <tr>
                <th scope="col" class="col-3">Actions</th>
                <th scope="col">@Html.ActionLink("Id", "Index", new { sortOrder = ViewBag.IdSortParm, currentFilter = ViewBag.CurrentFilter })</th>
                <th scope="col">@Html.ActionLink("Position", "Index", new { sortOrder = ViewBag.UserPositionNameSortParm, currentFilter = ViewBag.CurrentFilter })</th>
                <th scope="col">@Html.ActionLink("Action", "Index", new { sortOrder = ViewBag.UserActionNameSortParm, currentFilter = ViewBag.CurrentFilter })</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(" ", "Details", new { id = item.id }, new { @class = "btn btn-outline-info bi bi-eye" })
                        @Html.ActionLink(" ", "Edit", new { id = item.id }, new { @class = "btn btn-outline-warning bi bi-pencil" })
                        @Html.ActionLink(" ", "Delete", new { id = item.id }, new { @class = "btn btn-outline-danger bi bi-trash" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.user_position.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.user_action.name)
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</div>