cs-aspnet-mvc-crud/Models/user_position.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs_aspnet_mvc_crud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_position()
        {
            this.user = new HashSet<user>();
            this.user_permission = new HashSet<user_permission>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_permission> user_permission { get; set; }
    }
}

cs-aspnet-mvc-crud/Controllers/UserPositionController.cs
using System;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using System.Linq;
using cs_aspnet_mvc_crud.Models;
using cs_aspnet_mvc_crud.Middleware.Auth;
using PagedList;

namespace cs_aspnet_mvc_crud.Controllers
{
    public class UserPositionController : BaseController
    {
        // GET: UserPosition
        [UserAuthorization(userActionId: 11)]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.isAdmin = isAdmin;

            ViewBag.CurrentSort = sortOrder;
            ViewBag.IdSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var usersPositions = from o in entityModel.UserPosition select o;

            if (!String.IsNullOrEmpty(searchString))
            {
                usersPositions = usersPositions.Where(o => o.name.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "id_desc":
                    usersPositions = usersPositions.OrderByDescending(o => o.id);
                    break;
                case "name_desc":
                    usersPositions = usersPositions.OrderByDescending(o => o.name);
                    break;
                default:
                    usersPositions = usersPositions.OrderBy(o => o.id);
                    break;
            }
            int pageNumber = (page ?? 1);

            return View(usersPositions.ToPagedList(pageNumber, this.pageSize));
        }

        // GET: UserPosition
        [UserAuthorization(userActionId: 11)]
        public async Task<ActionResult> GetAll()
        {
            return View(await entityModel.UserPosition.ToListAsync());
        }

        // GET: UserPosition/Details/5
        [UserAuthorization(userActionId: 12)]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user_position user_position = await entityModel.UserPosition.FindAsync(id);
            if (user_position == null)
            {
                return HttpNotFound();
            }
            return View(user_position);
        }

        // GET: UserPosition/Create
        [UserAuthorization(userActionId: 13)]
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserPosition/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserAuthorization(userActionId: 13)]
        public async Task<ActionResult> Create([Bind(Include = "id,name,description")] user_position user_position)
        {
            if (ModelState.IsValid)
            {
                entityModel.UserPosition.Add(user_position);
                await entityModel.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(user_position);
        }

        // GET: UserPosition/Edit/5
        [UserAuthorization(userActionId: 14)]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user_position user_position = await entityModel.UserPosition.FindAsync(id);
            if (user_position == null)
            {
                return HttpNotFound();
            }
            return View(user_position);
        }

        // POST: UserPosition/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [UserAuthorization(userActionId: 14)]
        public async Task<ActionResult> Edit([Bind(Include = "id,name,description")] user_position user_position)
        {
            if (ModelState.IsValid)
            {
                entityModel.Entry(user_position).State = EntityState.Modified;
                await entityModel.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(user_position);
        }

        // GET: UserPosition/Delete/5
        [UserAuthorization(userActionId: 15)]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user_position user_position = await entityModel.UserPosition.FindAsync(id);
            if (user_position == null)
            {
                return HttpNotFound();
            }
            return View(user_position);
        }

        // POST: UserPosition/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [UserAuthorization(userActionId: 15)]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            user_position user_position = await entityModel.UserPosition.FindAsync(id);
            entityModel.UserPosition.Remove(user_position);
            await entityModel.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                entityModel.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

cs-aspnet-mvc-crud/Views/UserPosition/Create.cshtml
@model cs_aspnet_mvc_crud.Models.user_position

@{
    ViewBag.Title = "Create";
    ViewBag.Model = "User Position";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="col mx-auto">
        <div class="p-4 p-md-5 border rounded-3 bg-light">
            <h4>@ViewBag.Title @ViewBag.Model</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group mb-3">

                <div class="control-label">Name</div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>

                <div class="control-label">Description</div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>

            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-lg btn-dark" })
                    <input type="submit" value="Add" class="btn btn-lg btn-success" />
                </div>
            </div>
        </div>
    </div>
}

cs-aspnet-mvc-crud/Views/UserPosition/Delete.cshtml
@model cs_aspnet_mvc_crud.Models.user_position

@{
    ViewBag.Title = "Delete";
    ViewBag.Model = "User Position";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="col mx-auto">
        <div class="p-4 p-md-5 border rounded-3 bg-light">
            <h4>@ViewBag.Title @ViewBag.Model</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)

            <div class="form-group mb-3">

                <div class="control-label">Name</div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>

                <div class="control-label">Description</div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>

            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-lg btn-dark" })
                    <input type="submit" value="Save Changes" class="btn btn-lg btn-primary" />
                </div>
            </div>
        </div>
    </div>
}

cs-aspnet-mvc-crud/Views/UserPosition/Details.cshtml
@model cs_aspnet_mvc_crud.Models.user_position

@{
    ViewBag.Title = "Details";
    ViewBag.Model = "User Position";
}

<div class="col mx-auto">
    <div class="p-4 p-md-5 border rounded-3 bg-light">

        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">@ViewBag.Title @ViewBag.Model</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    @Html.ActionLink("Return", "Index", null, new { @class = "btn btn-sm btn-dark bi bi-backspace" })
                </div>
            </div>
        </div>

        <div class="accordion mb-3" id="accordionOne">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button text-white bg-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        @ViewBag.Title of this @ViewBag.Model
                    </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionOne">
                    <div class="accordion-body">
                        <div class="container">
                            <div class="row">
                                <div class="col-3"><b>Id</b></div>
                                <div class="col">@Html.DisplayFor(model => model.id)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Name</b></div>
                                <div class="col">@Html.DisplayFor(model => model.name)</div>
                            </div>
                            <div class="row">
                                <div class="col-3"><b>Description</b></div>
                                <div class="col">@Html.DisplayFor(model => model.description)</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

cs-aspnet-mvc-crud/Views/UserPosition/Edit.cshtml
@model cs_aspnet_mvc_crud.Models.user_position

@{
    ViewBag.Title = "Edit";
    ViewBag.Model = "User Position";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="col mx-auto">
        <div class="p-4 p-md-5 border rounded-3 bg-light">
            <div class="alert alert-danger" role="alert">
                Are you sure you want to delete this @ViewBag.Model?
            </div>

            <div class="accordion mb-3" id="accordionOne">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                        <button class="accordion-button text-white bg-danger" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            @ViewBag.Title this @ViewBag.Model
                        </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionOne">
                        <div class="accordion-body">
                            <div class="container">
                                <div class="row">
                                    <div class="col-3"><b>Id</b></div>
                                    <div class="col">@Html.DisplayFor(model => model.id)</div>
                                </div>
                                <div class="row">
                                    <div class="col-3"><b>Name</b></div>
                                    <div class="col">@Html.DisplayFor(model => model.name)</div>
                                </div>
                                <div class="row">
                                    <div class="col-3"><b>Description</b></div>
                                    <div class="col">@Html.DisplayFor(model => model.description)</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-lg btn-dark" })
                    <input type="submit" value="Delete" class="btn btn-lg btn-danger" />
                </div>
            </div>

        </div>
    </div>
}

cs-aspnet-mvc-crud/Views/UserPosition/Index.cshtml
@model PagedList.IPagedList<cs_aspnet_mvc_crud.Models.user_position>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Users Positions";
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">@ViewBag.Title</h1>

    @using (Html.BeginForm("Index", "UserPosition", FormMethod.Get))
    {
        <div class="input-group">
            <input type="submit" class="btn btn-outline-secondary" value="Search" />
            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", placeholder = "Input name" })
        </div>
    }

    <div class="btn-toolbar mb-2 mb-md-0">
        @Html.ActionLink("Add", "Create", null, new { @class = "btn btn-success bi bi-plus-circle" })
    </div>
</div>

<div class="table-responsive">
    <table class="table table-hover caption-top">
        <caption>@ViewBag.Title</caption>
        <thead>
            <tr>
                <th scope="col" class="col-3">Actions</th>
                <th scope="col">@Html.ActionLink("Id", "Index", new { sortOrder = ViewBag.IdSortParm, currentFilter = ViewBag.CurrentFilter })</th>
                <th scope="col">@Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })</th>                
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(" ", "Details", new { id = item.id }, new { @class = "btn btn-outline-info bi bi-eye" })
                        @Html.ActionLink(" ", "Edit", new { id = item.id }, new { @class = "btn btn-outline-warning bi bi-pencil" })
                        @Html.ActionLink(" ", "Delete", new { id = item.id }, new { @class = "btn btn-outline-danger bi bi-trash" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</div>